### ISSUE TITLE
Include build-essential in luarocks images

### ISSUE THREAD

**Issue by s-ol** [GUI/lua-docker#1]
A very large fraction of luarocks modules are C modules that have to be compiled, which requires a functioning toolchain (`build-essential` on debian, `alpine-sdk` on alpine).

**EDIT:** actually I see you are installing and removing gcc, make etc. in the builds. maybe it would be enough to just skip this cleanup step for luarocks images?

**Comment by GUI** [comment]
@s-ol: I'd prefer to keep these images minimal, so that's why I didn't include the dependencies for building C modules. If you're only installing pure-Lua dependencies from LuaRocks, then you don't need those compilers or build tools, so that's why I had opted to remove them from the final images. There may also be dependencies beyond `build-essential` needed, depending on what specific packages you're trying to install, so that's why I thought it might be best to leave the installation of those dependencies up to the user.

But I can see how this might be a common issue, so thanks for filing the issue! I've attempted to clarify this in the README with additional instructions: https://github.com/GUI/lua-docker#installing-c-libraries But let me know if you have any other suggestions or feedback. Thanks!
